name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
       cd ./vue-android
       ./gradlew build
       #sudo apt install tree
       #tree
       pwd
       ls
       
    - name : Upload
      uses: actions/upload-artifact@master
      with:
        name: app-debug.apk
        path: /home/runner/work/vue-demo/vue-demo/vue-android/build/outputs/apk/debug/app-debug.apk
 
    - name : Upload
      uses: actions/upload-artifact@master
      with:
        name: app-release-unsigned.apk
        path: /home/runner/work/vue-demo/vue-demo/vue-android/app/build/outputs/apk/release/app-release-unsigned.apk
